version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: jobeet-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=jobeet
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - 3306:3306

    webserver:
        build:
            context: .
            dockerfile: docker/ci/nginx/Dockerfile
        container_name: jobeet-webserver
        ports:
            - 80:80

    php-fpm:
        build:
            context: .
            dockerfile: docker/ci/php-fpm/Dockerfile
        container_name: jobeet-php-fpm
        environment:
            - APP_SECRET=143d58a6cfca1f3d63812b40d7576382

